# Generated by Django 5.2.17 on 2026-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normalized_query",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "provider_response_subset",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("resolved", "Resolved"),
                            ("unresolved", "Unresolved"),
                            ("failed", "Failed"),
                        ],
                        default="resolved",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                (
                    "origin_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("profile", models.CharField(default="driving", max_length=32)),
                ("provider_name", models.CharField(default="OSRM", max_length=32)),
                ("distance_miles", models.FloatField()),
                ("duration_seconds", models.FloatField()),
                ("geometry", models.JSONField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opis_truckstop_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("rack_id", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=512)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                ("state", models.CharField(blank=True, default="", max_length=8)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "normalized_identity",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("unresolved", "Unresolved"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "geocode_failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_row_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state"], name="routes_fuel_state_172b38_idx"),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="routes_fuel_latitud_203dad_idx",
                    ),
                ],
            },
        ),
    ]
